server:
  port: 8000

spring:
  application:
    name: helpdesk-pro

## DataSource
  datasource:
    url: jdbc:mysql://localhost:3306/helpdesk_pro?useSSL=false&serverTimezone=UTC
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
